### ISSUE TITLE
The PowerShell script failed to execute

### ISSUE THREAD

**Issue by rajeeshmenoth** [Azure-Samples/service-fabric-dotnet-management-party-cluster#12]
Hi, I am getting below error when publish the application in to party cluster. here is the VS 2017 output

Error occurred while restoring NuGet packages: The operation failed as details for project votingData could not be loaded.
1>------ Build started: Project: votingWeb, Configuration: Debug Any CPU ------
2>------ Build started: Project: votingData, Configuration: Debug Any CPU ------
1>Waiting for output folder cleanup...
2>Waiting for output folder cleanup...
2>Output folder cleanup has been completed.
1>Output folder cleanup has been completed.
2>votingData -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingData\bin\Debug\netcoreapp2.0\win7-x64\votingData.dll
1>votingWeb -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingWeb\bin\Debug\netcoreapp2.0\win7-x64\votingWeb.dll
3>------ Build started: Project: HmDemoApp, Configuration: Debug x64 ------
4>------ Publish started: Project: HmDemoApp, Configuration: Debug x64 ------
4>Started executing script 'GetApplicationExistence'.
-------- Package started: Project: HmDemoApp, Configuration: Debug x64 ------
4>Finished executing script 'GetApplicationExistence'.
4>Time elapsed: 00:00:03.2737436
votingData -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingData\bin\Debug\netcoreapp2.0\win7-x64\votingData.dll
votingData -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingData\obj\Debug\netcoreapp2.0\win7-x64\PubTmp\Out\
votingWeb -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingWeb\bin\Debug\netcoreapp2.0\win7-x64\votingWeb.dll
votingWeb -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\votingWeb\obj\Debug\netcoreapp2.0\win7-x64\PubTmp\Out\
HmDemoApp -> C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\HmDemoApp\pkg\Debug
-------- Package: Project: HmDemoApp succeeded, Time elapsed: 00:01:26.4431933 --------
4>Started executing script 'Deploy-FabricApplication.ps1'.
4>powershell -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -Command ". 'C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\HmDemoApp\Scripts\Deploy-FabricApplication.ps1' -ApplicationPackagePath 'C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\HmDemoApp\pkg\Debug' -PublishProfileFile 'C:\Users\Rajeesh.raveendran\source\repos\HmDemoApp\HmDemoApp\PublishProfiles\Cloud.xml' -DeployOnly:$false -ApplicationParameter:@{} -UnregisterUnusedApplicationVersionsAfterUpgrade $false -OverrideUpgradeBehavior 'None' -OverwriteBehavior 'SameAppTypeAndVersion' -SkipPackageValidation:$false -ErrorAction Stop"
4>Copying application to image store...
4>Copy-ServiceFabricApplicationPackage : Operation timed out.
4>At C:\Program Files\Microsoft SDKs\Service 
4>Fabric\Tools\PSModule\ServiceFabricSDK\Publish-NewServiceFabricApplication.ps1:244 char:9
4>+         Copy-ServiceFabricApplicationPackage -ApplicationPackagePath  ...
4>+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4>    + CategoryInfo          : OperationTimeout: (:) [Copy-ServiceFabricApplicationPackage], TimeoutException
4>    + FullyQualifiedErrorId : CopyApplicationPackageErrorId,Microsoft.ServiceFabric.Powershell.CopyApplicationPackage
4> 
4>Finished executing script 'Deploy-FabricApplication.ps1'.
4>Time elapsed: 00:11:27.0447326
4>The PowerShell script failed to execute.
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by rajeeshmenoth** [comment]
Hi,
The following way I resolved the above issue.
1) Restored all the NuGet packages
2) PowerShell open as "Administrator" mode.

**Comment by danielharvey14** [comment]
Hello @rajeeshmenoth I am running into the same issue.  How did you get Visual studio to run/open powershell in "administrator" mode?  Just by running VS in administrator mode?

**Comment by danielharvey14** [comment]
@rajeeshmenoth Please disregard, I resolved my error.
