### ISSUE TITLE
ElasticSearchListener.EnsureIndexExists throws NullReferenceException

### ISSUE THREAD

**Issue by mcjeff** [Azure-Samples/service-fabric-dotnet-management-party-cluster#4]
The exception happens when accessing indexState.Settings. The reason seems to be that the IndexState class does not initialize the Settings property. The issue always happens when EnsureIndexExists is called.

**Comment by karolz-ms** [comment]
I have just fixed this with https://github.com/Azure-Samples/service-fabric-dotnet-management-party-cluster/commit/07d6a41fd9aef58f54f8426c7d87e89933b58d14

**Comment by karolz-ms** [comment]
Thanks for reporting though :-)
