### ISSUE TITLE
GC KeepAlive - unreachable code

### ISSUE THREAD

**Issue by loekd** [Azure-Samples/service-fabric-dotnet-management-party-cluster#5]
In [WebService.Program.cs](https://github.com/Azure-Samples/service-fabric-dotnet-management-party-cluster/blob/master/src/PartyCluster.WebService/Program.cs)  ln35 there's code that blocks the calling thread infinitely.

`Thread.Sleep(Timeout.Infinite);`

After that, there's a call to the GC that can't be reached.
`GC.KeepAlive(esListener);`

Same thing in [ClusterService](https://github.com/Azure-Samples/service-fabric-dotnet-management-party-cluster/blob/master/src/PartyCluster.ClusterService/Program.cs)

Swapping the lines would help.

**Comment by karolz-ms** [comment]
It is not very intuitive, but the call to GC.KeepAlive is exactly where it needs to be. It is not a method with a real body that does something to the GC. Instead, it is a hint to the compiler that the esListener should not be garbage-collected even though it is not used by anything in Program.cs file by the time Thread.Sleep(Infinite) is invoked.

In the next version of the library we will make the diagnostics pipeline implement IDisposable so you can wrap it in a using statement and GC.KeepAlive will no longer be necessary
